[build]
  command = "npx prisma generate && npm run build"
  publish = "dist"

[build.environment]
  PRISMA_CLIENT_ENGINE_TYPE = "binary"

[[plugins]]
  package = "@netlify/plugin-functions-install-node-modules"

[functions]
  node_bundler = "esbuild"

[functions.build]
  included_files = ["./prisma/schema.prisma"]
