[build]
  command = "npx prisma generate && npm run build"
  publish = "dist"
  environment = { PRISMA_CLIENT_ENGINE_TYPE = "binary" }

[functions]
  node_bundler = "esbuild"
  build = { included_files = ["./prisma/schema.prisma"] }
